# Site Settings
title: "42 Blog"
description: "testing how github pages work."
author: "ArturAntela"

# Build Settings
timezone: Europe/Lisbon
future: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - faraday-retry

